const env = import.meta.env;

export const config = {
  DEV: env.DEV,
  VITE_TEMPO: env.VITE_TEMPO,
  VITE_OPENAI_API_KEY: env.VITE_OPENAI_API_KEY,
  VITE_OPENAI_MODEL: env.VITE_OPENAI_MODEL,
  VITE_OPENAI_TEMPERATURE: env.VITE_OPENAI_TEMPERATURE,
  VITE_OPENAI_MAX_TOKENS: env.VITE_OPENAI_MAX_TOKENS,
  VITE_OPENAI_TOP_P: env.VITE_OPENAI_TOP_P,
  VITE_OPENAI_FREQUENCY_PENALTY: env.VITE_OPENAI_FREQUENCY_PENALTY,
  VITE_OPENAI_PRESENCE_PENALTY: env.VITE_OPENAI_PRESENCE_PENALTY,
  VITE_SUPABASE_URL: env.VITE_SUPABASE_URL,
  SUPABASE_URL: env.SUPABASE_URL,
  VITE_SUPABASE_ANON_KEY: env.VITE_SUPABASE_ANON_KEY,
  SUPABASE_ANON_KEY: env.SUPABASE_ANON_KEY,
  VITE_SUPABASE_KEY: env.VITE_SUPABASE_KEY,
  VITE_SUPABASE_PROJECT_ID: env.VITE_SUPABASE_PROJECT_ID,
  SUPABASE_KEY: env.SUPABASE_KEY,
  VITE_BLOB_READ_WRITE_TOKEN: env.VITE_BLOB_READ_WRITE_TOKEN,
  BACKEND_URL:
    "https://liska-backend-gs49xhdta-claytons-projects-7c9b8210.vercel.app", //"https://api.lishka.dev",
  VITE_PUBLIC_POSTHOG_KEY: env.VITE_PUBLIC_POSTHOG_KEY,
  VITE_PUBLIC_POSTHOG_HOST: env.VITE_PUBLIC_POSTHOG_HOST,
};
